<?php
namespace Tenweb_Builder;

include_once TWBB_DIR . '/templates/base.php';

class SingleTemplate extends BaseTemplate {

  public static function get_slug(){
    return "twbb_single";
  }

  public static function get_title(){
    return 'Single';
  }


  public function save_type(){
    parent::save_type(); // TODO: Change the autogenerated stub
	//phpcs:ignore WordPress.Security.NonceVerification.Recommended
    if(!empty($_REQUEST['twbb-template-post-type'])) {
      //phpcs:ignore WordPress.Security.NonceVerification.Recommended
      $meta_value = sanitize_text_field($_REQUEST['twbb-template-post-type']);
      $this->update_meta('_twbb-template-post-type', $meta_value);
    }

  }

    public static function print_twbb_template($template_id, $templates = '') {
        $plugin       = \Elementor\Plugin::instance();
        $templateType = Templates::get_instance()->get_current_template_type();

        $targetTemplates = [
            'twbb_archive',
            'twbb_archive_products',
            'twbb_single_product',
            'twbb_single_post',
            'twbb_archive_posts',
            'twbb_slide',
        ];

        $isElementorPreview = $plugin->preview->is_preview_mode() && static::current_template();
        $isTargetTemplate   = in_array($templateType, $targetTemplates, true);

        if ( $isElementorPreview || $isTargetTemplate ) {
            // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
            echo $plugin->preview->builder_wrapper('');
        } else {
            self::print_builder_content($template_id);
        }
    }

}
