<?php
namespace Tenweb_Builder;
//phpcs:ignore WordPressVIPMinimum.Files.IncludingFile.NotAbsolutePath
include_once 'base.php';

class SingleProductTemplate extends BaseTemplate {

  public static function get_slug(){
    return "twbb_single_product";
  }

  public static function get_title(){
    return 'Single Product';
  }


  public function save_type(){
    parent::save_type(); // TODO: Change the autogenerated stub
	//phpcs:ignore WordPress.Security.NonceVerification.Recommended
    if(!empty($_REQUEST['twbb-template-post-type'])) {
      //phpcs:ignore WordPress.Security.NonceVerification.Recommended
      $meta_value = sanitize_text_field($_REQUEST['twbb-template-post-type']);
      $this->update_meta('_twbb-template-post-type', $meta_value);
    }

  }

	public static function print_twbb_template($template_id, $templates = "") {
		if( ( \Elementor\Plugin::instance()->preview->is_preview_mode() && static::current_template() ) ) {
			//phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
			echo \Elementor\Plugin::instance()->preview->builder_wrapper('');
		} else {
			self::print_builder_content($template_id);
		}
	}

}
